#include "..\script_component.hpp"

params [["_icon","",[""]]];

if (isNil QGVAR(iconHash)) then {
	GVAR(iconHash) = createHashMapFromArray [
		["@arrow_left",ICON_ARROW_LEFT],
		["@arrow_right",ICON_ARROW_RIGHT],
		["@boat",ICON_BOAT],
		["@box",ICON_BOX],
		["@car",ICON_CAR],
		["@cas",ICON_CAS],
		["@caution",ICON_CAUTION],
		["@checked",ICON_CHECKED],
		["@checked2",ICON_CHECKED2],
		["@clockwise",ICON_CLOCKWISE],
		["@composition",ICON_COMPOSITION],
		["@counter_clockwise",ICON_COUNTER_CLOCKWISE],
		["@destroy",ICON_DESTROY],
		["@drone",ICON_DRONE],
		["@east",ICON_EAST],
		["@flare",ICON_FLARE],
		["@gear",ICON_GEAR],
		["@gear2",ICON_GEAR2],
		["@get_out",ICON_GET_OUT],
		["@ground_support",ICON_GROUND_SUPPORT],
		["@group",ICON_GROUP],
		["@guer",ICON_GUER],
		["@gunship",ICON_GUNSHIP],
		["@hash",ICON_HASH],
		["@heli",ICON_HELI],
		["@home",ICON_HOME],
		["@home_pathing",ICON_HOME_PATHING],
		["@howitzer",ICON_HOWITZER],
		["@infinite",ICON_INFINITE],
		["@intel",ICON_INTEL],
		["@ir",ICON_IR],
		["@land",ICON_LAND],
		["@land_eng_off",ICON_LAND_ENG_OFF],
		["@laser",ICON_LASER],
		["@link",ICON_LINK],
		["@lock",ICON_LOCK],
		["@loiter",ICON_LOITER],
		["@map",ICON_MAP],
		["@minus",ICON_MINUS],
		["@missile",ICON_MISSILE],
		["@mortar",ICON_MORTAR],
		["@move",ICON_MOVE],
		["@move_eng_off",ICON_MOVE_ENG_OFF],
		["@mrls",ICON_MRLS],
		["@mrls_truck",ICON_MRLS_TRUCK],
		["@parachute",ICON_PARACHUTE],
		["@plane",ICON_PLANE],
		["@plus",ICON_PLUS],
		["@resupply",ICON_RESUPPLY],
		["@rope",ICON_ROPE],
		["@search",ICON_SEARCH],
		["@self_propelled",ICON_SELF_PROPELLED],
		["@slingload",ICON_SLINGLOAD],
		["@smoke",ICON_SMOKE],
		["@sort_down",ICON_SORT_DOWN],
		["@sort_none",ICON_SORT_NONE],
		["@sort_up",ICON_SORT_UP],
		["@sss",ICON_SSS],
		["@stop_vehicle",ICON_STOP_VEHICLE],
		["@strobe",ICON_STROBE],
		["@target",ICON_TARGET],
		["@terminal",ICON_TERMINAL],
		["@trash",ICON_TRASH],
		["@trigger_interval",ICON_TRIGGER_INTERVAL],
		["@unchecked",ICON_UNCHECKED],
		["@unchecked2",ICON_UNCHECKED2],
		["@unlock",ICON_UNLOCK],
		["@vtol",ICON_VTOL],
		["@wait",ICON_WAIT],
		["@wait_cycle",ICON_WAIT_CYCLE],
		["@wait_gear",ICON_WAIT_GEAR],
		["@west",ICON_WEST],

		// signals
		["@smoke_blue",ICON_SMOKE_BLUE],
		["@smoke_green",ICON_SMOKE_GREEN],
		["@smoke_red",ICON_SMOKE_RED],
		["@smoke_yellow",ICON_SMOKE_YELLOW],
		["@chem_blue",ICON_CHEM_BLUE],
		["@chem_green",ICON_CHEM_GREEN],
		["@chem_red",ICON_CHEM_RED],
		["@chem_yellow",ICON_CHEM_YELLOW],
		["@flare_green",ICON_FLARE_GREEN],
		["@flare_red",ICON_FLARE_RED],
		["@flare_yellow",ICON_FLARE_YELLOW]
	];
};

GVAR(iconHash) getOrDefault [toLower _icon,_icon]
